### ISSUE TITLE
Register the team in Space Apps website

### ISSUE THREAD

**Issue by ArielTEP** [ArielTEP/SpaceApps2020#2]
I assume we all have already created an account on the website but as far as I can tell, we haven´t created our team. Let´s do it together this week :3

**Comment by peguerosdc** [comment]
- Nombre completo: Carlos Pegueros Denis
- Nivel de escolaridad: licenciatura (concluida), maestría (in progress)
- Carrera, año o grado cursando: ing. en telemática, msc. en física. 2do año.
- Correo: (este si quieren sí me lo mandan por whatsapp)

**Comment by DouxLeonidas** [comment]
Nombre completo: Juan Leonardo Calderón Pérez
Nivel de escolaridad: Licenciatura
Carrera, año o grado cursando: Ingeniería en Sistemas Computacionales, 2017

**Comment by ArielTEP** [comment]
Entonces al final del día se quedó pendiente el registro? Si sí lo está, mañana nos registro en Create->Breakthrough si todos estan de acuerdo c:

**Comment by peguerosdc** [comment]
Sip, quedó pendiente el registro! Disculpa por desobligarnos, amigo :cry: gracias! eres da best :cupid:

**Comment by ArielTEP** [comment]
> Sip, quedó pendiente el registro! Disculpa por desobligarnos, amigo :cry: gracias! eres da best :cupid: 

No pasa nada papu, yo lo entiendo a la perfección <3. 
Voy saliendo del trabajo, ahorita en un chance hago el registro!

**Comment by peguerosdc** [comment]
https://2020.spaceappschallenge.org/challenges/create/breakthrough/teams/propulsioncraft/project
