### ISSUE TITLE
Get AWS setup ready

### ISSUE THREAD

**Issue by ArielTEP** [ArielTEP/SpaceApps2020#3]
Server-side setup / AWS - Lambda (Serverless) / Python - Flask / API / Dev server for now.
HelloWorld app... c:

**Comment by erikvquiterio** [comment]
This action was completed :)

**Comment by ArielTEP** [comment]
@erikvquiterio nice work bro. Can you open a pull request and put everybody as reviewers?
The idea is to close out this issue with your merge to 'develop' branch :3

**Comment by ArielTEP** [comment]
@erikvquiterio nice work bro. Can you open a pull request and put everybody as reviewers?
The idea is to close out this issue with your merge to 'develop' branch :3

**Comment by ArielTEP** [comment]
Never mind.
