### ISSUE TITLE
Register our team

### ISSUE THREAD

**Issue by ArielTEP** [ArielTEP/SpaceApps2020#6]
Para registrarnos, necesitaremos la siguiente info de cada integrante:

- Nombre completo
- Correo electrónico
- Nivel de escolaridad
- Carrera, grado o año que estamos cursando
- ¿Deseamos agregar más personas al equipo? Si/No
- Categoría en la que estamos interesados

Información más general como: Nombre del equipo, categoria y reto a resolver lo podemos determinar colectivamente por whatsapp. <3

**Comment by ArielTEP** [comment]
Ariel Tonatiuh Espindola Pizano
espindola.pizano@gmail.com
Licenciatura
Ing. en Telemática
No
Observe

**Comment by erikvquiterio** [comment]
Erik Velasco Quiterio
erikvelz@gmail.com
Licenciatura 
Informática
No
Observe

**Comment by ArielTEP** [comment]
Entonces en qué quedamos registrados? o está pendiente todavía? Si lo esta, mañana mismo nos registro en Create->Breakthrough si todos estan de acuerdo c:

**Comment by ArielTEP** [comment]
Duplicated with issue #2
